const GET_HUNT_REQUEST = "GET_HUNT_REQUEST";
const GET_HUNT_SUCCESS = "GET_HUNT_SUCCESS";
const GET_HUNT_FAILED = "GET_HUNT_FAILED";
const COUNTER_INCREMENT = "COUNTER_INCREMENT";
const COUNTER_DECREMENT = "COUNTER_DECREMENT";
const COUNTER_REST = "COUNTER_REST";

export {
    GET_HUNT_REQUEST,
    GET_HUNT_SUCCESS,
    GET_HUNT_FAILED,
    COUNTER_INCREMENT,
    COUNTER_DECREMENT,
    COUNTER_REST,
}